name: Build Homebrew bottles

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  bottle:
    strategy:
      fail-fast: false
      matrix:
        runner: [macos-13, macos-14]  # 13 ≈ Intel, 14 ≈ Apple Silicon
    runs-on: ${{ matrix.runner }}

    permissions:
      contents: write

    steps:
      - name: Checkout tap
        uses: actions/checkout@v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Style and audit formula
        run: |
          set -euo pipefail
          brew update
          brew style --fix .
          brew audit --formula --online --strict Formula/dcert.rb

      - name: Build bottle with test-bot
        env:
          TAP_REPO: ${{ github.repository }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          set -euo pipefail
          brew test-bot \
            --only-formulae \
            --tap="$TAP_REPO" \
            --keep-old \
            --fail-fast \
            --skip-recursive-dependents \
            --root-url="https://github.com/${TAP_REPO}/releases/download/${TAG_NAME}"

      - name: Upload bottles to the tag release
        uses: softprops/action-gh-release@v2
        if: always()  # publish artifacts even if one arch fails, so you can diagnose
        with:
          tag_name: ${{ github.ref_name }}
          files: "*.bottle.*"
          generate_release_notes: false
